<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latestMajor</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>False</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;IDE0051</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;IDE0051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="libs\**" />
    <EmbeddedResource Remove="libs\**" />
    <None Remove="libs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="R2API.ContentManagement" Version="1.0.11" />
    <PackageReference Include="R2API.Core" Version="5.3.0" />
    <PackageReference Include="R2API.Items" Version="1.0.8" />
    <PackageReference Include="R2API.Language" Version="1.1.0" />
    <PackageReference Include="R2API.Prefab" Version="1.1.1" />
    <PackageReference Include="R2API.RecalculateStats" Version="1.6.6" />
    <PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.1-r.0" />
    <PackageReference Include="RoR2BepInExPack" Version="1.43.0" />
    <PackageReference Include="Rune580.Mods.RiskOfRain2.RiskOfOptions" Version="2.8.6" />
    <PackageReference Include="MMHOOK.RoR2" Version="2025.12.9">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="score-MiscFixes" Version="1.5.9" />
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy /Y &quot;$(TargetDir)$(TargetName).dll&quot; &quot;$(SolutionDir)Release\$(TargetName).dll&quot;&#xD;&#xA;if exist $(SolutionDir)Release\Release.zip ( Del $(SolutionDir)Release\Release.zip)&#xD;&#xA;powershell Compress-Archive -Path '$(SolutionDir)Release\*.*' -DestinationPath '$(SolutionDir)Release\Release.zip' -Force" />
	</Target>

</Project>
